import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TokenProvider } from "@/context/TokenContext";
import { FetchProvider } from "@/context/FetchContext";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FetchProvider>
          <TokenProvider>
            <div>
              <Suspense fallback={<div>Loading...</div>}>
                <Navbar />
              </Suspense>
              <div className="max-w-screen-2xl mx-auto">
                {children}
              </div>
            </div>
          </TokenProvider>
        </FetchProvider>
      </body>
    </html>
  );
}
