import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TokenProvider } from "@/context/TokenContext";
import { FetchProvider } from "@/context/FetchContext";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import { CartProvider } from "@/context/CartContext";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FetchProvider>
          <TokenProvider>
            <CartProvider>
              <Suspense fallback={<Image src={"/container-loader-unscreen.gif"} width={100} height={100} alt='Image' />}>
                <Navbar />
              </Suspense>
              <div className="max-w-screen-2xl mx-auto">
                {children}
              </div>
            </CartProvider>
          </TokenProvider>
        </FetchProvider>
      </body>
    </html>
  );
}
